openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Fact Service
paths:
  /fact:
    get:
      summary: Gets a Random Fact
      operationId: getFact
      tags:
        - fact
      responses:
        '200':
          description: A random fact.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Fact"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Fact:
      type: object
      required:
        - id
        - text
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string